EPOCH: 200 
BATCH_SIZE: 1   # 2 for bert
ACCUMULATION_STEPS: 2   # 1 for bert
GRAPH_LR: 3e-5 # 5e-5 for bert
LR: 3e-5 # 5e-5 for bert
RA_LAYERS: 1
HIDDEN_DIM: 1024 # 768 for bert

MODEL:
  PLM_NAME: 'roberta-large' # 'bert-base-cased' for bert

DATA:
  DATASET: 'DWIE'
  NUM_CLASSES: 66
  MAX_LENGTH: 2500

DGRAPH:
  LAYERS_NUM: 2
