EPOCH: 40 # 40 for bert
BATCH_SIZE: 4 # 4 for bert
ACCUMULATION_STEPS: 1  # 1 for bert
GRAPH_LR: 3e-5 # 5e-5 for bert
LR: 3e-5 # 5e-5 for bert
RA_LAYERS: 1
HIDDEN_DIM: 1024 # 768 for bert

MODEL:
    PLM_NAME: 'roberta-large' # 'bert-base-cased' for bert

DATA:
    DATASET: 'DocRED'
    NUM_CLASSES: 97
    MAX_LENGTH: 1024

SGRAPH:
    LAYERS_NUM: 2
